### ISSUE TITLE
Strange results.

### ISSUE THREAD

**Issue by sunwoo76** [IsaacCorley/pytorch-enhance#10]
Thanks for your good work.

But, when I try to use your library, this makes
![sr_test](https://user-images.githubusercontent.com/38250239/122870258-65a05d00-d368-11eb-8945-8261c7ac4faa.png)
 strange results.

I loaded the image using openCV and made it pytorch tensor which range is [0.,1.]

Is the default is un-trained model?

I followed this example below:

import torch
import torch_enhance

increase resolution by factor of 2 (e.g. 128x128 -> 256x256)
model = torch_enhance.models.SRResNet(scale_factor=2, channels=3)

lr = torch.randn(1, 3, 128, 128)
sr = model(x) # [1, 3, 256, 256] ->  model(my_img)

**Comment by isaaccorley** [comment]
The default models are randomly initialized (untrained) so this is expected functionality.

**Comment by sunwoo76** [comment]
@isaaccorley 
thank you. Do you have a plan to upload pertained model weights?

**Comment by isaaccorley** [comment]
Yes, I'm working on a branch to which adds pretrained weights but don't have a time of completion for you.

**Comment by sunwoo76** [comment]
@isaaccorley 
I see. I hope you to update the pre-trained weights someday  :)
thank you!
