### ISSUE TITLE
Using bicubic model results in ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by robmarkcole** [IsaacCorley/pytorch-enhance#12]
Using `model = Bicubic(scale_factor, channels)` results in:

![image](https://user-images.githubusercontent.com/11855322/135280757-437efcad-0eec-4d08-ad73-9f4983b0d7d3.png)

I realise this model is not for training, but wish to get the PSNR on the test dataset for use as baseline. Is it valid to just do `trainer.test(module, test_dataloader)` ?

**Comment by isaaccorley** [comment]
Yeah you can't actually train the Bicubic model because it has no learnable parameters so you would just do inference or test.

**Comment by robmarkcole** [comment]
OK thanks. Interestingly my test_psnr result was better for bicubic than for srcnn & espcnn in my quick trial..!

**Comment by isaaccorley** [comment]
Yeah I've experienced the same with SRCNN but not ESPCN. I've had better results by using a small learning rate with SGD and training for longer. Sometimes PSNR can be relatively the same but visually the models produce better results compared to interpolation.
